name: CI_TESTS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ASPNETCORE_ENVIRONMENT: Test

jobs:
  TEST:
    name: Run all tests in scope
    runs-on: windows-latest
    steps:
    - name: Checkout GITHub branch
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build the app
      run: dotnet build
    - name: Run all tests in scope
      run: dotnet test --filter FullyQualifiedName!~TribesTests.IntegrationTests
